### PR TITLE
Add missing rosinstall dependencies

### PR DESCRIPTION
**Pull request by nicholasadr**
Requires extra repositories as dependencies: criutils and lkh

### CODE REVIEW

**Comment by fsuarez6** [comment]
What Ubuntu and ROS are you using?

**Comment by nicholasadr** [comment]
Ubuntu 16.04 and ROS Kinetic

**Comment by fsuarez6** [comment]
That's strange. Those packages should be available in the main repositories ([criutils](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=criutils) and [lkh](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=lkh))

Did you update your dependencies?
```bash
sudo apt-get update
cd ~/catkin_ws/src
rosdep install --from-paths . --ignore-src
```

**Comment by nicholasadr** [comment]
I did:

rosdep update
rosdep install --from-paths . --ignore-src -y

as mentioned in the installation guideline
https://crigroup.github.io/robotsp/install.html

**Pull request closed without merging**
